In [1]:
import pandas as pd
from pandas import DataFrame
import numpy as np

from IPython.core.display import display, HTML

display(HTML("<style>.container{width:100% ! important;}</style>"))
# pandas 출력 설정

pd.set_option('display.max_rows', 300)
pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 1000)
pd.describe_option()

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
display.chop_threshold : float or None
    if set to a float value, all float values smaller then the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]
display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]
display.column_space No description available.
    [default: 12] [currently: 12]
display.date_dayfirst : boolean
    When True, prints and parses dates with the day first, eg 20/01/2005
    [default: False] [currently: False]
display.date_yearfirst : boolean
    When True, prints and parses dates with the year first, eg 2005/01/20
    [default: False] [currently: False]
display.encoding : str/unicode
    Defaults to the detected encoding of the console.
    Specifies the encoding to be used for strings returned by to_string,
    these are generally strings meant to be displayed on the console.
    [default: UTF-8] [currently: UTF-8]
display.expand_frame_repr : boolean
    Whether to print out the full DataFrame repr for wide DataFrames across
    multiple lines, `max_columns` is still respected, but the output will
    wrap-around across multiple "pages" if its width exceeds `display.width`.
    [default: True] [currently: True]
display.float_format : callable
    The callable should accept a floating point number and return
    a string with the desired format of the number. This is used
    in some places like SeriesFormatter.
    See formats.format.EngFormatter for an example.
    [default: None] [currently: None]
display.html.border : int
    A ``border=value`` attribute is inserted in the ``<table>`` tag
    for the DataFrame HTML repr.
    [default: 1] [currently: 1]
display.html.table_schema : boolean
    Whether to publish a Table Schema representation for frontends
    that support it.
    (default: False)
    [default: False] [currently: False]
display.html.use_mathjax : boolean
    When True, Jupyter notebook will process table contents using MathJax,
    rendering mathematical expressions enclosed by the dollar symbol.
    (default: True)
    [default: True] [currently: True]
display.large_repr : 'truncate'/'info'
    For DataFrames exceeding max_rows/max_cols, the repr (and HTML repr) can
    show a truncated table (the default from 0.13), or switch to the view from
    df.info() (the behaviour in earlier versions of pandas).
    [default: truncate] [currently: truncate]
display.latex.escape : bool
    This specifies if the to_latex method of a Dataframe uses escapes special
    characters.
    Valid values: False,True
    [default: True] [currently: True]
display.latex.longtable :bool
    This specifies if the to_latex method of a Dataframe uses the longtable
    format.
    Valid values: False,True
    [default: False] [currently: False]
display.latex.multicolumn : bool
    This specifies if the to_latex method of a Dataframe uses multicolumns
    to pretty-print MultiIndex columns.
    Valid values: False,True
    [default: True] [currently: True]
display.latex.multicolumn_format : bool
    This specifies if the to_latex method of a Dataframe uses multicolumns
    to pretty-print MultiIndex columns.
    Valid values: False,True
    [default: l] [currently: l]
display.latex.multirow : bool
    This specifies if the to_latex method of a Dataframe uses multirows
    to pretty-print MultiIndex rows.
    Valid values: False,True
    [default: False] [currently: False]
display.latex.repr : boolean
    Whether to produce a latex DataFrame representation for jupyter
    environments that support it.
    (default: False)
    [default: False] [currently: False]
display.max_categories : int
    This sets the maximum number of categories pandas should output when
    printing out a `Categorical` or a Series of dtype "category".
    [default: 8] [currently: 8]
display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 20] [currently: 100]
display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 50]
display.max_info_columns : int
    max_info_columns is used in DataFrame.info method to decide if
    per column information will be printed.
    [default: 100] [currently: 100]
display.max_info_rows : int or None
    df.info() will usually show null-counts for each column.
    For large frames this can be quite slow. max_info_rows and max_info_cols
    limit this null check only to frames with smaller dimensions than
    specified.
    [default: 1690785] [currently: 1690785]
display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 300]
display.max_seq_items : int or None
    when pretty-printing a long sequence, no more then `max_seq_items`
    will be printed. If items are omitted, they will be denoted by the
    addition of "..." to the resulting string.

    If set to None, the number of items to be printed is unlimited.
    [default: 100] [currently: 100]
display.memory_usage : bool, string or None
    This specifies if the memory usage of a DataFrame should be displayed when
    df.info() is called. Valid values True,False,'deep'
    [default: True] [currently: True]
display.min_rows : int
    The numbers of rows to show in a truncated view (when `max_rows` is
    exceeded). Ignored when `max_rows` is set to None or 0. When set to
    None, follows the value of `max_rows`.
    [default: 10] [currently: 10]
display.multi_sparse : boolean
    "sparsify" MultiIndex display (don't display repeated
    elements in outer levels within groups)
    [default: True] [currently: True]
display.notebook_repr_html : boolean
    When True, IPython notebook will use html representation for
    pandas objects (if it is available).
    [default: True] [currently: True]
display.pprint_nest_depth : int
    Controls the number of nested levels to process when pretty-printing
    [default: 3] [currently: 3]
display.precision : int
    Floating point output precision (number of significant digits). This is
    only a suggestion
    [default: 6] [currently: 6]
display.show_dimensions : boolean or 'truncate'
    Whether to print out dimensions at the end of DataFrame repr.
    If 'truncate' is specified, only print out the dimensions if the
    frame is truncated (e.g. not display all rows and/or columns)
    [default: truncate] [currently: truncate]
display.unicode.ambiguous_as_wide : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.unicode.east_asian_width : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.width : int
    Width of the display in characters. In case python/IPython is running in
    a terminal this can be set to None and pandas will correctly auto-detect
    the width.
    Note that the IPython notebook, IPython qtconsole, or IDLE do not run in a
    terminal and hence it is not possible to correctly detect the width.
    [default: 80] [currently: 1000]
io.excel.ods.reader : string
    The default Excel reader engine for 'ods' files. Available options:
    auto, odf.
    [default: auto] [currently: auto]
io.excel.xls.reader : string
    The default Excel reader engine for 'xls' files. Available options:
    auto, xlrd.
    [default: auto] [currently: auto]
io.excel.xls.writer : string
    The default Excel writer engine for 'xls' files. Available options:
    auto, xlwt.
    [default: auto] [currently: auto]
io.excel.xlsb.reader : string
    The default Excel reader engine for 'xlsb' files. Available options:
    auto, pyxlsb.
    [default: auto] [currently: auto]
io.excel.xlsm.reader : string
    The default Excel reader engine for 'xlsm' files. Available options:
    auto, xlrd, openpyxl.
    [default: auto] [currently: auto]
io.excel.xlsm.writer : string
    The default Excel writer engine for 'xlsm' files. Available options:
    auto, openpyxl.
    [default: auto] [currently: auto]
io.excel.xlsx.reader : string
    The default Excel reader engine for 'xlsx' files. Available options:
    auto, xlrd, openpyxl.
    [default: auto] [currently: auto]
io.excel.xlsx.writer : string
    The default Excel writer engine for 'xlsx' files. Available options:
    auto, openpyxl, xlsxwriter.
    [default: auto] [currently: auto]
io.hdf.default_format : format
    default format writing format, if None, then
    put will default to 'fixed' and append will default to 'table'
    [default: None] [currently: None]
io.hdf.dropna_table : boolean
    drop ALL nan rows when appending to a table
    [default: False] [currently: False]
io.parquet.engine : string
    The default parquet reader/writer engine. Available options:
    'auto', 'pyarrow', 'fastparquet', the default is 'auto'
    [default: auto] [currently: auto]
mode.chained_assignment : string
    Raise an exception, warn, or no action if trying to use chained assignment,
    The default is warn
    [default: warn] [currently: warn]
mode.sim_interactive : boolean
    Whether to simulate interactive mode for purposes of testing
    [default: False] [currently: False]
mode.use_inf_as_na : boolean
    True means treat None, NaN, INF, -INF as NA (old way),
    False means None and NaN are null, but INF, -INF are not NA
    (new way).
    [default: False] [currently: False]
mode.use_inf_as_null : boolean
    use_inf_as_null had been deprecated and will be removed in a future
    version. Use `use_inf_as_na` instead.
    [default: False] [currently: False]
    (Deprecated, use `mode.use_inf_as_na` instead.)
plotting.backend : str
    The plotting backend to use. The default value is "matplotlib", the
    backend provided with pandas. Other backends can be specified by
    prodiving the name of the module that implements the backend.
    [default: matplotlib] [currently: matplotlib]
plotting.matplotlib.register_converters : bool or 'auto'.
    Whether to register converters with matplotlib's units registry for
    dates, times, datetimes, and Periods. Toggling to False will remove
    the converters, restoring any converters that pandas overwrote.
    [default: auto] [currently: auto]

In [2]:
Developer_data = pd.read_csv('../../data/Developer.csv')

In [3]:
Developer_data

             Developer  project_count  Estimated_time_sum  Estimated_time_avg  issue_count  Android  IOS  Admin page  Mobile Web  RWD Web  Server  PC Web  DB  Android Studio  Swift  HTML/CSS  PHP  PHP - Larabel  Javascript  React Native  NodeJS  Kotlin  React  MySQL  AngularJS  Ruby on Rail  VueJS  Python Django  Server AWS  PHP - CodeIgniter  POSTGre  Server Cafe24  Python Flask  Ubuntu  Linux  ASP  .NET  MSSQL  object-c  JSP/Java  Docker  Wordpress  CentOS  Appcenter (for app auto Distribution)  Java Spring  NodeJS Express  PHP - GNU board
0     datteam.anh_quoc              1              335.20           14.573913           23        1   22           0           0        0       0       0   0               0     23         0    0              0           0             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
1     datteam.Phong_it              3              482.00            8.169492           59       59    0           0           0        0       0       0   0              47      0         0    0              0           0             0       0      12      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
2           Hon_Nguyen              6              265.00            3.680556           72        0    0          41           1        1      29       1  21               0      0         3   28              0           1             0      20       0     11      9          2             0      0              0           3                  0        0              0             0       3      0    0     0      0         0         0       0          0       0                                      0            0               0                0
3           Tuan_Trong              8              279.00            4.650000           60        1   59           0           0        0       0       0   0               1     59         0    0              0           0             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
4   NguyenTeam_TrungDo              1               98.40            3.280000           30       29   27           0           1        0       0       0   0               0      0         0    4              0           0            29       0       0     29      1          0             0      0              0           0                  1        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
5    NguyenTeam_DucTho              1              105.60            5.028571           21        1    0           7           1        0      13       0   1               0      0         1   20              0           1             0       0       0      0      1          0             0      0              0           1                  3        0              0             0       0      0    0     0      0         0         0       0          0       1                                      0            0               0                0
6          Hien_Nguyen              5              277.20            3.797260           73       70    1           2           0        0       0       0   0              45      3         0    0              0           0             0       0      26      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
7            Ngoc_Pham              6              234.00            3.295775           71        1    0          17           0       26      28       0   5               1      0         4    0              0           3             0      18       0     22      4          2             0      0             13           0                  0        6              0             8       0      1    0     0      0         0         0       2          0       0                                      0            1               2                0
8         Khanh_Nguyen              9              446.50            7.087302           63        1   62           0           0        0       0       0   0               0     61         0    0              0           0             1       0       0      1      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
9              Tran_Vu              2              146.00            4.562500           32        0    0           0           0       32       0       0   0               0      0        32    0              0           1             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
10             Hung_Le              7              356.46            5.569687           64        0    0           0           9        9       2      45   0               0      0        62    1              0          18             0       0       0      0      0          0             0      0              0           1                  0        0              0             0       0      0    0     0      0         0         0       0          1       0                                      0            0               0                0
11          Sunny_Nhut             23              713.95            4.890068          146      144   24           1           0        0       1       0   1             118      1         0    0              0           0            23       0       4     23      0          0             0      0              0           0                  0        1              0             2       0      0    0     0      0         0         0       0          0       0                                      0            1               0                0
12      An_Tinh_Nguyen              1              174.00            9.666667           18        0   18           0           0        0       0       0   0               0     18         0    0              0           0             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
13        Duc_Tran_AOS              1              180.00            9.473684           19       19    0           0           0        0       0       0   0              19      0         0    0              0           0             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         1       0          0       0                                      0            0               0                0
14           Tri_Thien              4               89.00            4.684211           19        0    0           3          10        3       6       8   2               0      0         6   13              0           5             0       0       0      0      0          0             0      0              0           0                  3        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
15             SR_HOST             19             1627.00            8.175879          199       41   18          68          23       34      19      20  25              39     17        30   76              0          20             0      32       0      0     29          1             3      0              0           2                  0        0              2             0       0      2    0     0      0         0         3       0          0       0                                      0            0               0                1
16          Suong_Tran              2               78.40            3.920000           20        0    0           7           0        0      11       0   3               0      0         0    0              0           0             0       0       0      0      0          0            12      0              0           0                  0        0              0             0       0      0    1     2      3         0         0       0          0       0                                      0            3               0                0
17           Hieu_Tran             10              813.00           18.477273           44        0    1           7          20        4       0      18   0               0      1        38    1              0          28             0       0       0      0      0          0             0      4              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
18          Nam_Nguyen              1               57.60           57.600000            1        0    0           1           0        0       0       0   0               0      0         0    1              0           0             0       0       0      0      0          0             0      0              0           0                  1        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
19          Duy_Nguyen              6              453.00            4.398058          103        2  100           0           0        0       0       0   1               1    101         0    0              0           0             0       0       0      0      1          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
20                문정_최              1                2.00            2.000000            1        0    0           0           0        0       1       0   0               0      0         0    0              0           1             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         1       0          0       0                                      0            0               0                0
21          Hoang_Cong              2              480.00           26.666667           18        0    0           5           0        0       8       5   1               0      0         0    8              0           1             0       0       0      0      1          0             0      9              0           0                  0        0              1             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
22          Hyejin_Lee              2               63.00            2.863636           22        0    0           0          15        0       6       0   1               0      0         7   14              0           6             0       0       0      0      1          0             0      0              0           0                  0        0              0             0       0      1    0     0      0         0         0       0          0       0                                      0            0               0                0
23    Nhan_Truong_Vinh              1               74.00            4.933333           15        0    0           0          15        0       0       0   0               0      0         0    0              0           0             0       0       0      0      0         15             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
24            Khanh_Vo              1               10.00           10.000000            1        0    0           0           0        1       0       0   0               0      0         1    0              0           1             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
25            Duc_Tran              1               10.00           10.000000            1        0    0           0           0        1       0       0   0               0      0         1    0              0           1             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
26            Hao_Tang              1                2.00            2.000000            1        0    0           0           0        1       0       0   0               0      0         0    0              0           1             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
27            Lam_Tran              5              336.00           15.272727           22        3   22           0           0        0       0       0   0               3     22         0    0              0           0             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
28            dat_tran              2              236.50            5.141304           46       46    0           0           0        0       0       0   0              46      0         0    0              0           0             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
29         Wayne_Hoang              1               35.00           35.000000            1        0    1           0           0        0       0       0   0               0      1         0    0              0           0             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
30           Tung_Tran              2               73.00            6.636364           11        0   11           0           0        0       0       0   0               0      4         0    0              0           0             7       0       0      7      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
31         Danny_huynh              3               57.40            4.100000           14       12    0           1           0        0       0       0   1              12      0         0    0              0           0             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    1     1      0         0         0       0          0       0                                      0            0               0                0
32         Thai_Nguyen              4               38.50            2.406250           16        0   14           1           0        0       1       0   0               0     15         0    2              0           0             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
33            Tuan_Ngo              1                8.00            8.000000            1        0    0           0           0        1       0       0   0               0      0         0    0              0           0             0       0       0      0      0          1             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0
34             Big_Tam              9              285.50            5.190909           55       55    6           0           0        0       0       0   0              55      6         0    0              0           1             0       0       0      0      0          0             0      0              0           0                  0        0              0             0       0      0    0     0      0         0         0       0          0       0                                      0            0               0                0

In [6]:
# 절대값을 가지는 경우의 계산
df = Developer_data[['Developer', 'Estimated_time_sum', 'Estimated_time_avg', 'issue_count']]
df

             Developer  Estimated_time_sum  Estimated_time_avg  issue_count
0     datteam.anh_quoc              335.20           14.573913           23
1     datteam.Phong_it              482.00            8.169492           59
2           Hon_Nguyen              265.00            3.680556           72
3           Tuan_Trong              279.00            4.650000           60
4   NguyenTeam_TrungDo               98.40            3.280000           30
5    NguyenTeam_DucTho              105.60            5.028571           21
6          Hien_Nguyen              277.20            3.797260           73
7            Ngoc_Pham              234.00            3.295775           71
8         Khanh_Nguyen              446.50            7.087302           63
9              Tran_Vu              146.00            4.562500           32
10             Hung_Le              356.46            5.569687           64
11          Sunny_Nhut              713.95            4.890068          146
12      An_Tinh_Nguyen              174.00            9.666667           18
13        Duc_Tran_AOS              180.00            9.473684           19
14           Tri_Thien               89.00            4.684211           19
15             SR_HOST             1627.00            8.175879          199
16          Suong_Tran               78.40            3.920000           20
17           Hieu_Tran              813.00           18.477273           44
18          Nam_Nguyen               57.60           57.600000            1
19          Duy_Nguyen              453.00            4.398058          103
20                문정_최                2.00            2.000000            1
21          Hoang_Cong              480.00           26.666667           18
22          Hyejin_Lee               63.00            2.863636           22
23    Nhan_Truong_Vinh               74.00            4.933333           15
24            Khanh_Vo               10.00           10.000000            1
25            Duc_Tran               10.00           10.000000            1
26            Hao_Tang                2.00            2.000000            1
27            Lam_Tran              336.00           15.272727           22
28            dat_tran              236.50            5.141304           46
29         Wayne_Hoang               35.00           35.000000            1
30           Tung_Tran               73.00            6.636364           11
31         Danny_huynh               57.40            4.100000           14
32         Thai_Nguyen               38.50            2.406250           16
33            Tuan_Ngo                8.00            8.000000            1
34             Big_Tam              285.50            5.190909           55
35      Nghia_Le_Trong              180.00           12.857143           14
36         Hailey_Hoan               33.70            5.616667            6

In [ ]:
project_estimated_time = 4